### ISSUE TITLE
Upgrade to A16?

### ISSUE THREAD

**Issue by hopeseekr** [jaxxa/ED-Stargate#2]
I'm willing to sponsor an upgrade to A16. 

Let me know if it is possible and if so how much money you would want.

**Comment by jaxxa** [comment]
Thanks for the offer but I am not taking money to update my mods currently. I will look into updating it but it probably need a rework.

Is there a reason that you want A16 specifically and not A17 preview?
Do you see this used to just move between different colonies on the same planet or to separate save games?

**Comment by hopeseekr** [comment]
Either is OK ;-)

I simply will not play Rimworld without this mod. I'm stuck without you!

**Comment by hopeseekr** [comment]
ANYYY HOPE of it coming back? :( I'm still stuck on an old version of rimworld :rotating_light:

**Comment by jaxxa** [comment]
So, obviously I didn't get around to updating it yet, sorry about that. 
I have recently got back into updating some of my mods with the release of B18.
My current intention is to create a spiritual sucessor to this mod themed around StarTrek Transporters and initially focusing on just moving around the one panet.
I might be able to have it done for this coming weekend, depending on what happens.

**Comment by jaxxa** [comment]
The new mod is not ready for release yet but is getting close.

The Github for the new mod is: https://github.com/jaxxa/ED-Transporter

I am asking for balancing ideas here: https://ludeon.com/forums/index.php?topic=37158.45
